version: '3.9'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "80:80"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
